- misc/kube-system/configmap/aws-auth.yaml
참고: https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/add-user-role.html
이미 `kubectl apply -f misc/kube-system/configmap/aws-auth.yaml`는 적용했고, 기록용으로 남깁니다. `misc` dir 내부는 commit 한다고 자동 반영되거나 하지 않습니다.
앞으로 이 사람들이 계속 `system:masters`을 갖는 것은 아니고, 일정 시점 후부터는 wafflestudio infra admin 분들만 남는 것으로 생각하면 됩니다.
cluster 생성자는 기본으로 `system:masters`을 갖는데, [aws guide](https://aws.amazon.com/ko/premiumsupport/knowledge-center/amazon-eks-cluster-access/) 에 굳이 명시하지 않는 게 가장 좋다고 해서, 저 자신을 주석으로만 명시했습니다.
**뭐든지 가능한 권한을 가지신 셈이므로, 주의해서 이용해주세요.**
> Add wafflestudio-clsuter admin to mapUsers of aws-auth configmap as system:masters

- misc/addons/load-balancer-controller/load-balancer-controller.yaml
- misc/kube-system/metrics-server/components.yaml
`kubectl top pod`가 가능하게 하는 metrics-server 생성 yaml 추가
https://github.com/kubernetes-sigs/metrics-server
thanks to @PFCJeong
> Add metrics-server yaml

- apps/snutt-prod/snutt-ev/snutt-ev.yaml
prod snutt-core 도 eks 로 와서, cluster 내부 통신이 가능해졌으므로, `snutt-ev-api.wafflestudio.com`는 swagger 에 대해서만 접근할 수 있도록 하여 보안 강화
> Allow only swagger endpoint for prod snutt-ev

- misc/apps/snutt-dev/snutt-dev.yaml
- misc/apps/snutt-prod/snutt-prod.yaml
- misc/kube-system/configmap/aws-auth.yaml
snutt 팀 멤버들은 kubectl 이용을 원하는 경우가 있어서 권한 부여하고, [kubectl 이용 가이드](https://www.notion.so/wafflestudio/kubectl-WIP-c62498c8e7a042fba49fe94ed1143f02)를 대충 작성해보았습니다. 와플 전체에 대해 이렇게 할지는 고민이 더 필요할 거 같습니다. 의견 남겨주셔도 좋습니다.
> Grant snutt-dev, snutt-prod pod permissions to snutt members

- apps/truffle-prod/truffle/truffle.yaml
지금 보니 `allowOrigin`도 되고 `allowOrigins`도 되는 거 같네요. 두 개가 문법이 다름.
> allow all origins for truffle

- apps/snutt-dev/snutt-core/snutt-core.yaml
- apps/truffle-prod/truffle/truffle.yaml
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1674542012894069?thread_ts=1674539768.222069&cid=C0PAVPS5T
- content-type 이 x-www-urlencoded 가 아닌 json 인 경우 cors 이슈가 있어서 허용 header 로 추가해줘야함
- 신규 API 인 bookmarks 에 대해선 반드시 /v1/* 을 붙인 것만 받아줌
> [snu4t] Allow content-type header to allowHeaders of corsPolicy and Modify bookmarks routing

- apps/snutt-dev/snutt-core/snutt-core.yaml
- apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-dev/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- snutt-prod 에서 bookmarks API 는 snutt-timetable 로 routing 하도록 변경
- VirtualService routing 마다 적절한 naming 부여
- NodePort 이던 snutt Service 들 ClusterIP 로 변경 (https://github.com/wafflestudio/waffle-world/pull/26#discussion_r1069320836)
> prod snutt core routing & clusterip service

- .github/CODEOWNERS
- apps/pupuri-prod/pupuri-bot.yaml
- apps/pupuri/pupuri-bot.yaml
- apps/templates/pupuri-bot.yaml
pupuri slackbot 을 추가합니다. snutt-ev-web-dev 의 것을 많이 참고했습니다.
- [ECR](https://ap-northeast-2.console.aws.amazon.com/ecr/repositories/private/405906814034/pupuri/pupuri-bot?region=ap-northeast-2)
- [slack request](https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1679928566139959)
- [`#project-pupuri` slack channel](https://wafflestudio.slack.com/archives/C05021XHMQV)
> add pupuri

- charts/prometheus/Chart.lock
- charts/prometheus/Chart.yaml
- charts/prometheus/values.yaml
1. waffle-world 의 다른 charts 들처럼, `kube-prometheus-stack` helm chart 를 감싼 chart 를 정의해서 사용함.
2. grafana 에 github sso 를 적용함. (기존 admin pwd 는 좀 공유가 되어서 변경함.)
(이미 이 방식으로 chart 재설치 해본 상태입니다. https://grafana.wafflestudio.com )
> Enclose kube-prometheus-stack chart && Use github sso

- apps/ggzz-dev/ggzz-server/ggzz-server.yaml
- DB instance 정보 받아 local에서 연결 및 db/user 생성 후 관련 정보를 AWS Secrets Manager에 등록
1. `GgzzSecurityGroup` 생성 후 inbound로 192.168.0.0/16 (wafflestudio-vpc), outbound로 All traffic 열기
2. db 생성 / user 생성
3. dev/ggzz-server에 AWS RDS(mysql) user / password 등록
4. `GgzzSecretsManagerDev` Policy 생성 후 `ggzz-dev-role`에 부여
5. DB에 `ggzz-server` Deployment가 띄우는 image가 바라볼 수 있도록 ServiceAccount를 `waffle-world` manifest에 정의
> [FEATURE] ServiceAccount 추가: DB 연결용 SecretsManager 권한 role

- apps/snutt-dev/snutt-ev-batch/snutt-ev-batch.yaml
- apps/snutt-dev/snutt-ev/snutt-ev.yaml
- apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
- apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
- apps/snutt-prod/snutt-ev-batch/snutt-ev-batch.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
https://wafflestudio.slack.com/archives/C04T7UW3U8G/p1683450147942169?thread_ts=1683449967.142629&cid=C04T7UW3U8G
로컬에서 dev profile 로 개발하는 경우가 있는데, application.yml 에 설정해두면 로컬 에러가 false alert 로 슬랙에 오는 경우가 있어서, application.yml 설정에선 빼고, 배포 환경의 환경 변수로 설정해서, k8s 환경에서만 truffle-kotlin sdk 동작하게 함.
> TRUFFLE_ENABLED=true for snutt-ev, snu4t

- charts/prometheus/values.yaml
프로메테우스 스토리지가 기본 세팅 (EmptyDir) 사용, 파드 재시작 시 유실 위험이 있었음
PV 사용하도록 설정하면 좋겠다 싶었음
`prometheus-kube-prometheus-prometheus` 서비스의 파드 조회하고 디비 볼륨 & 마운트 상황 파악해봄
https://grafana.wafflestudio.com/ 에서 볼륨 사용량이 보이지 않아서 (찾지 못해서)
아래 방법으로 조회 후 설정 그대로 config에 넣어봤어요
```
➜  ~ kc describe pod prometheus-prometheus-kube-prometheus-prometheus-0 -n prometheus
Mounts:
/etc/prometheus/certs from tls-assets (ro)
/etc/prometheus/config_out from config-out (ro)
/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 from prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 (rw)
/etc/prometheus/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
/prometheus from prometheus-prometheus-kube-prometheus-prometheus-db (rw)
/var/run/secrets/kubernetes.io/serviceaccount from …
```
> [suggestion] replace prometheus storage from EmptyDir to PVC

- charts/prometheus/values.yaml
helm 차트 수정
적용된 것 확인하고 올려요. 🙏 
아니 아래 문서에서 필드 이름이 `storage` 로 되어있었음 ㅠㅠ
https://github.com/prometheus-community/helm-charts/issues/186
이거 보고 Spec 붙여서 다시 적용했습니다
> [FIX] update yaml field on prometheusSpec

- apps/sso-prod/kong-gateway/kong-config.yaml
- apps/sso-prod/kong-gateway/kong-gateway.yaml
- apps/truffle-prod/truffle-dashboard/truffle-dashboard.yaml
truffle.wafflestudio.com/api/* 요청이 kong-gateway (w/ waffle-jwt-authorizer plugin) 을 통해서 가도록 함
> truffle-dashboard 서버를 kong-gateway 뒤에 위치시키기

- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
snutt-ev-web 이 트래픽 많을 때 좀 이슈가 있는 거 같아서 (직접적으로 메모리 이슈인지 확신 X), 약간 빠듯하긴 한 듯해 올림
> Increase snutt-ev-web memory

- apps/snutt-prod/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
수강편람 최초 등록 시 푸시 받고 많은 유저가 진입해서 7월 3일(월)에 장애 발생했었음. 급한대로 수동으로 일부 서비스 replicas 를 2로 늘려서 대응했으나, 자동으로 빠르게 대응하고자 함.
HPA 쓰는 경우 ArgoCD 가 replicas 갖고 auto sync 하면 안 되니까 주석 처리
https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#leaving-room-for-imperativeness
이 설정대로라면 cpu requests 의 80% 평균을 맞추도록 scaling 함
> Set HPA for Snutt Services

- apps/snutt-dev/snutt-core/snutt-core.yaml
- apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-dev/snutt-ev/snutt-ev.yaml
- apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
- apps/snutt-prod/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
snutt-ev-web 이 socket 끊어져서 아무 요청 못 받고 있는데, pod 재시작도 안 되고 있던 문제가 있었습니다.
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1688382668501989
이에 각 application 에 health-check endpoint 추가하고 liveness, readiness probe 설정합니다. 일단 initialDelaySeconds 는 따로 주지 않았습니다.
> Set probes for snutt services

- apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-dev/snutt-ev/snutt-ev.yaml
- apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
probes 들이 자꾸 500 나서 앱 뜨자마자 `timeoutSeconds: 1`이 짧나 싶어서 증가
> timeoutSeconds for probes

- apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-dev/snutt-ev/snutt-ev.yaml
- apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
related #97, #93 
시작이 느릴 수 있는 application 들을 위해, startupProbe 설정. container 를 실패로 간주하고 너무 빠르게 재시작하는 것 방지.
> set startupProbe for Snutt Services

- apps/snutt-dev/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-core/snutt-core.yaml
snu4t 추가 migration 개발 진행에 따라, logout API, device APIs, notification APIs 를 dev, prod 에서 routing 변경
굳이 method 명시 안 해도 되는 경우 제거. 순서 일관성 있게 변경.
> Routes more apis to snu4t

- apps/snutt-dev/snutt-ev-batch/snutt-ev-batch.yaml
- apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
- apps/snutt-prod/snutt-ev-batch/snutt-ev-batch.yaml
dev, prod 가 동시에 떠서 한 순간에 메모리를 너무 많이 요구하는 상황 개선. 일부러 서로 간격을 둠.
snutt-timetable batch 이후 바로 snutt-ev batch 를 돌려서, 강의평 접근 시 lecture not found 나는 것을 줄임. 하루 1번에서 2번으로 더 자주 실행.
> snutt batch 시간 조정

- charts/argocd/Chart.lock
- charts/argocd/Chart.yaml
- charts/argocd/values.yaml
의존하는 argocd chart 버전 올림
prod nodegroup 에 할당되도록 함
덕분에 디자인도 바뀌었습니다 ㅋㅋ
> Upgrade argocd chart & Schedule to prod nodegroup

- apps/feelin-dev/feelin-core-server/feelin-core-server.yaml
- apps/feelin-dev/feelin-social-server/feelin-social-server.yaml
- apps/feelin-dev/feelin-web/feelin-web.yaml
- apps/feelin-prod/feelin-core-server/feelin-core-server.yaml
- apps/feelin-prod/feelin-social-server/feelin-social-server.yaml
- apps/feelin-prod/feelin-web/feelin-web.yaml
- misc/argocd/virtualservice.yaml
- misc/grafana/virtualservice.yaml
https://apps.apple.com/kr/app/feelin/id1665350212?l=en
- feelin-prod 는 유저가 사용하므로 prod nodegroup 에 배치
- feelin-dev 는 현재 개발 중단 상황이므로 replicas 0
- feelin 서버들 resources 설정 (JAVA_OPTS 관련해서는 wafflestudio/feelin-server#298 참고
- mesh 빠져있던 것들에 더 넣음
https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1687075623044219
> Schedule feelin-prod to prod nodegroup & Set Resources & etc

- apps/wacruit-dev/wacruit-judge/wacruit-judge-server.yaml
ruby on rails 가 기본으로 잡아먹는 메모리가 생각보다 많네요..
평소에 별 요청이 없을 때에도 상시로 200MiB에 언저리의 메모리를 점유하고 있는데 최대 메모리를 192MiB로 설정해둔 상태라 요청이 한두 건만 둘어와도 쉽게 터지는 상황입니다 ㅠ 50MiB 정도만 메모리 여유분을 추가해도 될까요??
> increase maximum value of memory of wacruit-dev-judge-server

- apps/sso-dev/kong-gateway/kong-config.yaml
- apps/sso-prod/kong-gateway/kong-config.yaml
wacruit-server 에서 클러스터 외부에서 보내는 요청들의 `request url` 이 kong-gateway를 지나며 cluster ip로 변조되는 이슈를 해결하기 위해 `preserve_host` 옵션을 추가하였습니다.
해당 옵션은 다빈님이 찾아주셨습니다 🧇 🧇 🧇 🙇 
https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcompreserve-host
> add preserve_host option to wacruit-service

- charts/argocd/values.yaml
AppProject 로 각 팀의 Application 들을 분리하고, AppProject 하위에 권한 policy 들을 예쁘게 정리하고 싶긴 했는데, 지금의 App of Apps 구조에서는 이게 간단히 테스트 및 적용해보는 게 쉽지가 않았습니다.
일단 각 팀 분들께 권한을 드려 각자 자율적인 관리를 더 편하게 빨리 해드리는 게 중요할 거 같고 사실 이 방식도 직관적이고 편한 점도 있어서, 예쁘진 않지만 권한 내용을 한 곳에 때려넣었습니다. 다른 팀들에게도 각 Application 들에 권한을 점차 다 넣어드릴 예정입니다.
Related: #49, https://github.com/wafflestudio/waffle-world/pull/119#issuecomment-1644109647
> argocd perm for waffledotcom, snutt

- apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
- apps/snutt-prod/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml
사실상 dev환경이 의미가 없기도 하고 (수강신청 기간에만 동작하기 때문) sugang snu 부하 줄까봐 dev환경 배치는 지움
> 빈자리 알림 prod환경 배포

- apps/snutt-prod/snutt-core/snutt-core.yaml
- apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
- apps/snutt-prod/snutt-ev/snutt-ev.yaml
- apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
grafana 에서 트래픽 튈 때 cpu 그래프 봤을 때, requets 대비 40% 정도로 target 을 잡아야 (또는 더 낮게) 유의미하게 스케일링될 것 같아서 줄임.
> hpa cpu target averageUtilization 조절

- apps/areyouhere/areyouhere-server/areyouhere-server.yaml
생각보다 스프링 서버가 켜지는 데 시간이 오래걸려서, 재시작이 반복되네요 ㅠ 해커톤 기간에는 해당 설정을 제외하고 추후 서버를 유지한다면 적절한 설정값을 고려해 보겠습니다!
> 와커톤 areyouhere 서버 health-check 삭제

- .github/CODEOWNERS
- apps/babble/babble-server/deployment.yaml
- apps/babble/babble-server/istio.yaml
- apps/babble/babble-server/service.yaml
- apps/templates/babble-server.yaml
- misc/apps/namespace.yaml
안녕하세요. 와카톤 babble팀 k8s 초기 셋업 작업입니다.
현재 [babble-server 저장소](https://github.com/wafflestudio/babble-server/actions
)에 프로젝트 빌드 후 ECR로 푸시하는 깃헙 액션 셋업되었고, 이미지가 제대로 푸시되는 것까지 확인 완료되었습니다. 
- 현재 이미지 태그는 `1`입니다.
- 환경변수는 빌드 시점에 깃헙 액션 secrets에서 가져와 주입합니다.
CODEOWNERS에는 일단 제 깃헙 id를 추가했습니다.
실수하거나 놓친 부분이 있으면 알려주시기 바랍니다. 감사합니다.
> setup babble namespace and argocd

- .github/CODEOWNERS
- charts/argocd/values.yaml
argocd babble, icebreaker 팀이 자신의 application 제어 권한 갖도록 함.
겸사겸사 argocd server memory 증가.
> argocd permissions for icebreaker, babble

- charts/argocd/values.yaml
- 식샤 백엔드, 데이터 관련 분들에게 `siksha-crawler{-dev}`에 정의되어 있는 cronjob을 수동으로 실행시킬 수 있도록 하기 위한 권한 추가
- 해당 동작에 대한 권한이 아래 pr을 통해 추가되었는데, 현재 waffle-world의 argo-helm 버전이 해당 pr이 머지되기 전 버전으로 알고 있습니다.
- 이로 인해 지금 권한 부여 방식이 동작하지 않는다면 모든 namespace에 대한 application create 권한을 주던가 argo-helm의 버전을 올려야 될 거 같은데 이 부분은 고민이 필요해보입니다.
- 관련 슬랙 링크: https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1731308194095139
- argo-helm cronjob create 관련 pr 링크: https://github.com/argoproj/argo-helm/pull/2212
> siksha-server-dev 팀에 대하여 cronjob 수동 실행 권한 부여

- .github/CODEOWNERS
- apps/internhasha-dev/internhasha/internhasha-server.yaml
- apps/internhasha-prod/internhasha/internhasha-server.yaml
- apps/templates/internhasha-dev.yaml
- apps/templates/internhasha.yaml
- misc/apps/namespace.yaml
인턴하샤 서버인 internhasha-server 배포를 위한 PR입니다.
[서버 레포](https://github.com/wafflestudio/internhasha-server)입니다.
다음 두 PR을 참고하여 작성하였습니다. 이번에 처음 작성하게 되어 부족한 부분이 있을 수 있습니다.
- https://github.com/wafflestudio/waffle-world/pull/190
- https://github.com/wafflestudio/waffle-world/pull/162
+ startupProbe 부분은 spring actuator 적용, 세 엔드포인트 모두 확인하였습니다.
이번 PR과 관련된 질문을 몇 가지 드립니다!
1. CODEOWNERS의 @wafflestudio/internhasha 팀 설정이 아직 안 되어 있습니다. 직접 팀 생성이 안 되는 것 같은데 인프라 팀에 요청하여 생성하면 되는 것인지 궁금합니다.
2. 개발과 배포 각각의 이미지는 임시로 ecr에 올린 이미지를 지정하였습니다. 앞으로 태그 기반으로 업데이트를 할 예정인데, 아직 [ecr-heimdall](https://github.com/wafflestudio/ecr-heimdall)에 대한 설정이 되어 있지 않습니다. 만약 해당 레포 적용 없이 업데이트를 하려면 waffle-world에 매번 pr을 하여 갱신을 하여야하는지 궁금합니다.(혹시 다른 방법이 있을까요?)
3. cpu, memory 스펙은 일단 다른 manifest 파일을 참고해가며 임의로 설정하였습니다. 현재 단계에서 이 정도면 충분할까요?
- dev는 …
> Add internhasha-server

- apps/internhasha-dev/internhasha/internhasha-server.yaml
- apps/internhasha-prod/internhasha/internhasha-server.yaml
- 아래 이벤트 로그에서 보이는 노드 메모리 부족으로 인한 파드 추가 실패를 방지하기 위해 dev 서버의 요청 메모리를 감소시켰습니다.
> 0/7 nodes are available: 2 Insufficient memory, 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {phase: prod}. preemption: 0/7 nodes are available: 2 No preemption victims found for incoming pod, 5 Preemption is not helpful for scheduling.
> [인턴하샤] dev 서버 메모리 조정

- apps/wacruit-prod/wacruit-server/wacruit-server.yaml
- charts/argocd/templates/argocd-notifications-cm.yaml
- charts/argocd/values.yaml
- `helm upgrade argocd charts/argocd -f charts/argocd/values.yaml -n argocd --dry-run --debug` 명령 수행시 아래와 같은 로그가 발생하였습니다
- 수정을 위해, `charts/argocd/values.yaml`에 nil-pointer 방지를 위하여 `app:` 블록을 추가하였습니다.
```
> helm upgrade argocd charts/argocd -f charts/argocd/values.yaml -n argocd --dry-run --debug
upgrade.go:142: [debug] preparing upgrade for argocd
coalesce.go:175: warning: skipped value for argocd.argo-cd.redis-ha.affinity: Not a table.
coalesce.go:223: warning: destination for argocd.argo-cd.redis-ha.haproxy.affinity is a table. Ignoring non-table value ()
coalesce.go:223: warning: destination for argo-cd.redis-ha.haproxy.affinity is a table. Ignoring non-table value ()
coalesce.go:175: warning: skipped value for argo-cd.redis-ha.affinity: Not a table.
Error: UPGRADE FAILED: template: …
```
> Infra : argocd/values.yaml 에 app, namespace argocd 추가

- misc/kube-system/configmap/aws-auth.yaml
인프라팀 활동 종료하신 분들의 IAM 계정 권한을 삭제하는 PR입니다!
커밋은 기록용이고 별도로 kubectl apply할 예정입니다.
> aws-auth.yaml에서 졸업생 IAM 제거

- .github/CODEOWNERS
- k8s-monitoring 에 waffle-k8s-admin 추가
- internhasha, memowithtags 삭제 (기존에 팀이 github에 존재하지 않아서 오류가 났고, 둘 다 개발 중단 예정)
> CODEOWNERS 수정

- apps/k8s-monitoring/k8s-monitoring-app/app.yaml
ecr 정리할때 0.0.1 이미지가 삭제돼서 현재 imagepullbackoff 상태라 ecr에 올라가 있는 0.0.3으로 버전을 바꿨습니다.
> fix: k8s-monitoring 이미지 버전

- apps/memowithtags-prod/memowithtags/memowithtags-server.yaml
memowithtags의 prod 서버를 사용하기 위해 replicas를 1로 조정하였습니다.
> memowithtags - prod replicas를 1로 조정
