charts/argocd/values.yaml

`helm upgrade argocd charts/argocd -n argocd --wait` 로 적용

argocd github sso

---

apps/snutt-dev/snutt-core/snutt-core.yaml

왜 waffle-world-bot 일 안하나요
113 올렸어요 ㅠㅠ

snutt-core-dev 최신버전 배포

---

charts/argocd/values.yaml

초기 세팅 끝났으므로 admin 계정 로그인 disable
`helm upgrade argocd charts/argocd -n argocd --wait`으로 적용 예정

argocd admin disabled

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-dev/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml

ReplicaSet 이 기본이 history 로 10개 남아있는데, 4개로 줄임.

Set revisionHistoryLimit as 4 for Deployments

---

misc/istio/telemetry.yaml

This PR resolves #5 issue.
https://istio.io/latest/docs/tasks/observability/telemetry/
https://istio.io/latest/docs/tasks/observability/logs/access-log/
`kubectl apply -f misc/istio/telemetry.yaml`으로 적용.

istio telemetry for istio-proxy access log

---

.github/CODEOWNERS
apps/seminar/android-project-backend/android-project-backend.yaml
apps/templates/seminar-android-project-backend.yaml
misc/apps/namespace.yaml

- Rookies 2022 Android 세미나를 위한 @sanggggg 의 백엔드 설정
- sso-prod namespace 는 겸사겸사 추가

Add app seminar/android-project-backend & sso-prod namespace

---

.github/CODEOWNERS
apps/snutt-dev/snutt-ev-batch/snutt-ev-batch.yaml
apps/snutt-prod/snutt-ev-batch/snutt-ev-batch.yaml

Add Env and ServiceAccount for snutt-ev-batch

---

apps/siksha-prod/siksha-api-server/siksha-api-server.yaml

https://wafflestudio.slack.com/archives/C01L208ELKT/p1673611176536519?thread_ts=1672929825.314369&cid=C01L208ELKT

remove k8s suffix for prod domain

---

apps/snutt-dev/snutt-core/snutt-core.yaml

[snu4t] feat: add corsPolicy

---

.github/CODEOWNERS
apps/templates/truffle.yaml
apps/truffle-prod/truffle/truffle.yaml
misc/apps/namespace.yaml

https://github.com/wafflestudio/truffle main branch 용 prod 자동 배포 설정

Deploy truffle prod

---

apps/snutt-dev/snutt-core/snutt-core.yaml

options이 뭔가 잘 안동작해서 요거는 일단 snutt에 위임하는게 좋을 듯.
virtualservice corsPolicy 안써본 기능인데 뚝딱거리네요. 
독스를 좀 자세히 읽어볼게요.

remove OPTIONS in regex

---

.github/CODEOWNERS
apps/feelin-dev/feelin-core-server/feelin-core-server.yaml
apps/feelin-dev/feelin-social-server/feelin-social-server.yaml
apps/feelin-prod/feelin-core-server/feelin-core-server.yaml
apps/feelin-prod/feelin-social-server/feelin-social-server.yaml
apps/feelin-prod/feelin-web/feelin-web.yaml
apps/templates/feelin-core-server-dev.yaml
apps/templates/feelin-core-server.yaml
apps/templates/feelin-social-server-dev.yaml
apps/templates/feelin-social-server.yaml
apps/templates/feelin-web.yaml
misc/apps/namespace.yaml

feat: Add feelin prod environment

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

Fix routing ordering (#39)

---

apps/webgam-dev/webgam-server/webgam-server.yaml

- 환경변수 설정
- 포트 변경 (80 -> 8080)

Webgam Server Dev

---

apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
apps/templates/snutt-timetable-batch-dev.yaml

snutt-timetable-batch-dev 가 사용할 SA 가 적용되어있지 않아 pod 가 실행되지 못하는 문제 수정
snutt-timetable-batch 를 snutt-timetable-batch-dev 로 더 적절하게 이름 수정

snutt-timetable-batch-dev fixed

---

apps/snutt-dev/snutt-core/snutt-core.yaml

- @wafflestudio/snutt 의 [시간표 공유기능](https://github.com/wafflestudio/snutt-timetable/pull/22)을 위한 path를 추가합니다

add path for shared tables

---

apps/seminar/android-project-backend/android-project-backend.yaml

https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1682521472363889?thread_ts=1670143745.551259&cid=C01M4TMNFPX
이제 안 쓰는 거 같아서 pod 제거

Make replicas of android-project-backend 0

---

.github/CODEOWNERS
apps/ggzz-dev/ggzz-server/ggzz-server.yaml
apps/templates/ggzz-server-dev.yaml
misc/apps/namespace.yaml

- 프로젝트명 변경에 따른 EKS 관련 사항 수정 Commit 입니다.
- code owners 및 namespace 반영이 필요합니다.

[REFACTOR] nostalgia -> ggzz

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

cors option for snu4t prod routing

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

https://wafflestudio.slack.com/archives/C052DL4F3C0/p1683560060122889?thread_ts=1683549923.698029&cid=C052DL4F3C0

[dev] Rewrite path for snu4t

---

apps/snutt-dev/snutt-core/snutt-core.yaml

#62 처럼 하니까 안 되어서, 일단 의도한 동작이 되게 해보는 것을 목표로 수정해봄. 당연히 이대로면 유지보수와 가독성이 매우 별로라 개선 필요.
kong gateway 등 api gateway 를 써서 더 rewrite 를 예쁘게 하든가, cors 를 snu4t 가 직접 처리해서 route rule 마다 cors 주렁주렁 안 달아도 되게 하든가 해야할 듯.

[dev] fix snutt routing rewrite

---

.github/CODEOWNERS
apps/siksha-dev/siksha-api-server/siksha-api-server.yaml
apps/templates/siksha-api-server-dev.yaml

식샤 api server의 dev 환경 구축하고자 합니다.
route53 레코드 연결
ECR
dev서버용 리소스 접근 권한 가진 siksha-api-server-dev-role 세팅 완료해 두었습니다.

feat: added siksha dev env

---

apps/snutt-dev/snutt-core/snutt-core.yaml

v1 optional 하게 처리해야 함
migration endpoint 끼리 모이게 순서 조절함

Fix snutt-dev route spec

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

prod GET /tables route

---

apps/seminar/android-project-backend/android-project-backend.yaml
apps/sso-dev/account-server/account-server.yaml
apps/sso-dev/kong-gateway/kong-gateway.yaml
apps/webgam-dev/webgam-server/webgam-server.yaml

https://github.com/wafflestudio/waffle-world/pull/26#discussion_r1062202291 논의에 따라 변경

nodeport to clusterip

---

apps/snutt-dev/snutt-ev-batch/snutt-ev-batch.yaml
apps/snutt-prod/snutt-ev-batch/snutt-ev-batch.yaml

wafflestudio/snutt-ev#87 관련해서 JOB_NAMES -> JOB_NAME 으로 snutt-timetable 과 일관되게 바꿈.

Modify snutt-ev batch env

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-dev/snutt-ev/snutt-ev.yaml
apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1684806361577219?thread_ts=1684800314.725879&cid=C0PAVPS5T
@PFCJeong 선생의 말씀.
> vs에다가 request timeout을 설정하는게 좋을 거 같은데 어떠신가요?
그래서, 했습니다. 사실 30s 도 긴데 얼마로 넣을지 고민이긴 합니다. 디폴트는 timeout 이 없는 상태였습니다.
https://istio.io/latest/docs/reference/config/networking/virtual-service/

Set VirtualService Timeout for SNUTT

---

apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml
apps/truffle-prod/truffle-dashboard/truffle-dashboard.yaml

chore: 스웨거 지원을 위한 vs 설정 (truffle)

---

.github/CODEOWNERS
apps/templates/waffledotcom-server-dev.yaml
apps/templates/waffledotcom-server.yaml
apps/waffledotcom-dev/waffledotcom-server/waffledotcom-server.yaml
apps/waffledotcom-prod/waffledotcom-server/waffledotcom-server.yaml
misc/apps/namespace.yaml

현재 와플닷컴 프로젝트 세팅 단계에 있으며, ECR workflow [PR](https://github.com/wafflestudio/waffledotcom-server/pull/13)이 리뷰 대기중이므로 ECR 레포지토리는 비어 있는 상태입니다. (← 이 상태에서 머지해도 heimdall이 잘 처리해주나요? 아니라면 저 PR 머지될때까지 이 PR은 보류해도 됩니다.)
- Route53 설정 완료
- dev role 는 나중에 필요할 수도 있을 것 같긴 하지만 지금은 일단 제외
누락된 거, 고칠 거 있으면 알려주십쇼 🫡

Deploy waffledotcom-server dev & prod 

---

.github/CODEOWNERS
apps/sso-prod/account-server/account-server.yaml
apps/sso-prod/kong-gateway/kong-config.yaml
apps/sso-prod/kong-gateway/kong-gateway.yaml
apps/sso-prod/kong-gateway/kustomization.yaml
apps/templates/sso-account-server.yaml
apps/templates/sso-kong-gateway.yaml

최근 truffle, waffledotcom 쪽에서 사용할 니즈가 생겨서 sso-prod 환경을 준비합니다.
wafflestudio/waffle-account-server#54, wafflestudio/waffle-kong-gateway#8

Init sso-prod

---

apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml

dev 환경에 이슈가 좀 있는 거 같아서 grafana 에서 cpu throttling 보고 올림

Update snutt-ev-web-dev to increase cpu

---

apps/snutt-prod/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

Namespace 지정이 안 되어있어서 hpa 가 target 을 못 찾는다고 하길래 수정

Set hpa namspace

---

apps/siksha-dev/siksha-crawler/siksha-crawler.yaml
apps/siksha-prod/siksha-crawler/siksha-crawler.yaml
apps/templates/siksha-crawler-dev.yaml
apps/templates/siksha-crawler.yaml

기존 aws 람다에 올라가있던 크롤러를 K8S로 이전하고자 합니다.
아직 ecr에 이미지 푸시는 안된 상황이에요!

Siksha crawler

---

apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-dev/snutt-ev/snutt-ev.yaml
apps/snutt-dev/snutt-timetable/snutt-timetable.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

#85 에서 QoS `Guranteed`를 위해 cpu requests/limits 를 맞췄으나, application 초기 시작 시 cpu throttling 걸려서 너무 힘들어 하는 거 같아서 늘립니다.

increase cpu limits of snutt

---

README.md

Add k8s-monitoring to README.md

---

apps/snutt-dev/snutt-ev-batch/snutt-ev-batch.yaml

memory 부족으로 dev 만 실패해서 prod 와 맞춤
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1688741828353079

Increase snutt-ev-batch dev memory

---

apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml

Update snutt-timetable-batch dev for increasing memory

---

apps/siksha-prod/siksha-api-server/siksha-api-server.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

node OOM이 너무 자주 발생하여, 죽으면 안되는 중요 서버는 prod 노드로 이사 하려합니다. 
이사 완료

schedule snutt, siksha to prod node group

---

apps/sso-dev/kong-gateway/kong-config.yaml
apps/sso-prod/kong-gateway/kong-config.yaml
apps/wacruit-dev/wacruit-judge/wacruit-judge-server.yaml
apps/wacruit-prod/wacruit-judge/wacruit-judge-server.yaml
apps/waffledotcom-dev/waffledotcom-server/waffledotcom-server.yaml
apps/waffledotcom-prod/waffledotcom-server/waffledotcom-server.yaml

- kong-gateway 거칠 때 path strip 안하도록 수정했습니다. (https://github.com/wafflestudio/waffle-world/commit/b3a671979111141416fe713dd439b43dfe2b11b1)
- 현재 리쿠르팅 기간이 끝날때까지는 waffledotcom 개발 일시 중지상태여서, pod replica 개수 0으로 조정합니다. (https://github.com/wafflestudio/waffle-world/commit/ee1d6d2c41bed265b1eece66a9252cd2d03c392b)
- 디버깅 목적으로 judge server 에 대한 외부 트래픽을 일시적으로 허용하려고 합니다. (https://github.com/wafflestudio/waffle-world/commit/b8af92f77296197b608727587058d592e703569d)

Additional configuration for wacruit

---

apps/pupuri-prod/pupuri-bot/pupuri-bot.yaml
apps/siksha-dev/siksha-api-server/siksha-api-server.yaml
apps/siksha-prod/siksha-api-server/siksha-api-server.yaml
apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml

k8s 환경 안정화를 위해, 지속적으로 application 들의 resources 를 grafana 데이터 토대로 적절히 설정하고 있습니다.

Set or Adjust resources

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-dev/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-dev/snutt-ev/snutt-ev.yaml
apps/snutt-dev/snutt-timetable/snutt-timetable.yaml

dev nodegroup 만들어서 스누티티 먼저 이사갑니다.
구 노드그룹은 스케일 인할게요.

schedule snutt dev to dev node

---

charts/argocd/values.yaml
charts/prometheus/Chart.lock
charts/prometheus/Chart.yaml
charts/prometheus/values.yaml

dev, prod 외에 infra NodeGroup 도 만듭니다. 일단 ArgoCD 와 Prometheus, Grafana 를 옮깁니다.
Prometheus charts 도 겸사겸사 최신으로 업데이트. resources 설정도 필요한데, 그건 별개 PR 로 하겠습니다.

infra nodegroup

---

apps/webgam-dev/webgam-server/webgam-server.yaml

해당 팀에 확인 받고, 현재 개발 진행 안 하고 계셔서 0 으로 바꿔둡니다.
https://wafflestudio.slack.com/archives/C031X9YR38U/p1689999131162069

webgam-server ev replicas 0

---

apps/snutt-prod/snutt-core/snutt-core.yaml

아직 snu4t prod 배포가 있기 전이지만 미리 configs API routing 설정

prod snutt configs routing

---

apps/wacruit-prod/wacruit-judge/wacruit-judge-server.yaml
apps/wacruit-prod/wacruit-judge/wacruit-judge-worker.yaml
apps/wacruit-prod/wacruit-server/wacruit-server.yaml

waffle-world에 replica가 0인걸 깜빡하고 뒤늦게 올립니다..
늦은 시간에 요청드려서 죄송합니다 😥
혹시 이거 메모리/cpu 이대로 해도 괜찮을까요??
그라파나를 사용해본 적이 별로 없어서 어떻게 보는지 잘 모르지만 지난 24시간 기준 max capa에 여유가 좀 있는 것 같아서 충분히 여유분을 두고 올려보았습니다.

wacruit-prod 배포

---

charts/argocd/Chart.yaml
charts/argocd/values.yaml

related #49 
각 팀에 담당 application 에 대해, `kubectl exec`과 유사하게 pod 내 접속을 ArgoCD 내에서 가능하도록 함

argocd exec

---

apps/wacruit-dev/wacruit-judge/wacruit-judge-server.yaml
apps/wacruit-dev/wacruit-judge/wacruit-judge-worker.yaml
apps/wacruit-prod/wacruit-judge/wacruit-judge-server.yaml
apps/wacruit-prod/wacruit-judge/wacruit-judge-worker.yaml

wacruit-judge 를 현재 유료 api로 사용하고 있어서 replica를 0으로 해두겠습니다.

wacruit judge replica 0

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1691493013039049

snutt admin cors

---

apps/snutt-dev/snutt-timetable-batch/snutt-timetable-batch.yaml
apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml

Manual Triggered Batch Job
크론이 아니지만 관리를 위해 크론잡으로 정의함 
실행되지 않도록 시간설정 (2월 31일)
====
fyi. #129 도 한 번 확인해주시면 감사,,

snu4t userNickname update batch

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

SNUTT-app version header 허용

---

apps/snutt-prod/snutt-core/snutt-core.yaml

snutt users routing prod

---

charts/argocd/Chart.yaml

https://github.com/argoproj/argo-helm/pull/2268
#129

Argo 버전 업데이트 반영 (v2.8.4)

---

apps/snutt-dev/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-core/snutt-core.yaml

https://github.com/wafflestudio/waffle-world/commit/07bcec15558c3d5f44bac9afe75e10532bd9efa4
revert 하면서 이상한 부분 같이 수정
https://github.com/wafflestudio/snutt-timetable/issues/125
여기 적힌대로 prod환경도 마이그레이션함

snutt 라우팅 룰 정리

---

apps/coupong-prod/argo-application.yaml
apps/coupong-prod/coupong-server/coupong-server.yaml

[팀 포켓-쿠퐁](https://wafflestudio.slack.com/archives/C05TA804NTD/p1695455944885599) 이니시 걸어봅니다.

init coupong server

---

apps/seminar/react-project-backend/react-project-backend.yaml
apps/templates/seminar-react-project-backend.yaml
charts/argocd/values.yaml

- 2023 리액트 세미나 백엔드 추가
android-project-backend에서 무지성 복붙했습니다.
대충 sqlite + nodejs라는 구조도 비슷하고 앱 사이즈도 비슷할거라 리소스 세팅도 똑같이 해놓으면 될 거라고 생각합니다.
하나하나 뜯어보기엔 시간도 없고 머리도 아파서 잠깐 미뤄두도록 하겠습니다.

add react seminar backend

---

apps/waffledotcom-dev/waffledotcom-server/waffledotcom-server.yaml
apps/waffledotcom-prod/waffledotcom-server/waffledotcom-server.yaml

안녕하세요~
와플닷컴 v2 배포에 앞서 멤버 DB와의 연결을 위해 관련 API를 배포하고자 합니다.
현재로서는 멤버 리스트 조회, 슬랙에서 멤버 정보 동기화 정도가 전부인지라 큰 리소스가 필요할 것 같지않아 서버를 실행시키기 위한 최소한의 리소스만 추정하여 요청드립니다.
최소한의 스펙으로 요청드리다보니 따로 요청 근거는 산정하지 않았는데 필요하다면 말씀해주세요!!

와플닷컴 v2 배포를 위한 멤버 API 배포

---

apps/waffledotcom-dev/waffledotcom-server/waffledotcom-server.yaml
apps/waffledotcom-prod/waffledotcom-server/waffledotcom-server.yaml

waffledotcom-server 에 ServiceAccount 를 추가합니다.
현재 인프라에도 IAM 역할 추가 요청드린 상태이며, 해당 역할 생성된 후 이 PR도 머지하겠습니다.

와플닷컴 서비스 어카운트 추가

---

apps/templates/seeya-server.yaml
misc/apps/namespace.yaml

@davin111 확인 감사합니다!!
네임스페이스는 관리자가 수동으로 추가하는 거라고 하셔서 건들지 않았습니다.

seeya-server template 추가

---

.github/CODEOWNERS
apps/areyouhere/areyouhere-server/areyouhere-server.yaml
apps/templates/areyouhere-server.yaml
misc/apps/namespace.yaml

와커톤을 위한 areyouhere 서버 배포를 위한 PR입니다. 와플 인프라 사용 자체가 처음이다 보니 미숙한 점이 많은 것 같아 많은 피드백 부탁드립니다!
- ECR이 아직 발급되지 않아 주소 부분을 아직 작성하지 않았지만 검토를 위해 PR을 먼저 올립니다! ECR 발급된 후 github actions 또한 작성할 예정입니다. 
- 코드 오너는 저( @rayark1 ) 입니다. 아직 레포 권한이 없는 것 같아 fork 후 PR 진행하였습니다.
- 리소스 부분은 가늠이 잘 안되어, 다른 레포를 참고하여 작성하였습니다.
- 레포 주소는 다음과 같습니다. https://github.com/wafflestudio/areyouhere-server

add areyouhere-server

---

charts/argocd/values.yaml

https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1708092584440669?thread_ts=1707714902.449139&cid=C01M4TMNFPX
GitHub team 을 @JuTaK97 이 만들어주시면 merge 예정

seeya, sungo, areyouhere 팀에게 소유 application argocd 권한 부여

---

apps/areyouhere/areyouhere-server/areyouhere-server.yaml

Add areyouhere ecr image

---

apps/seminar/react-project-backend/react-project-backend.yaml

안 쓰니까 끄려고 합니다. replica만 0으로 바꿨는데 더 설정해야 할 게 있을까요?

리액트 세미나 백엔드 끄기

---

apps/areyouhere/areyouhere-server/areyouhere-server.yaml
apps/babble/babble-server/babble-server.yaml
apps/icebreaker/deploy/icebreaker.yaml
apps/snugo/snugo-server/snugo-server.yaml

@wafflestudio/babble , @wafflestudio/snugo , @wafflestudio/areyouhere , @wafflestudio/icebreaker  팀의 서버 pod을 0개로 조정합니다.

와커톤 팀 미사용 서버 pod 개수 조정

---

apps/snutt-prod/snutt-core/snutt-core.yaml
apps/snutt-prod/snutt-ev-web/snutt-ev-web.yaml
apps/snutt-prod/snutt-ev/snutt-ev.yaml
apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

thanks to @asp345 
k8s 버전 업그레이드로 api version 업데이트도 필요해짐
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1718714858527969?thread_ts=1718554243.038999&cid=C0PAVPS5T

update hpa api version

---

apps/snutt-dev/snutt-core/snutt-core.yaml

snutt dev email routing

---

apps/snutt-dev/snutt-timetable/snutt-timetable.yaml

Reverts wafflestudio/waffle-world#202
https://github.com/wafflestudio/snutt-timetable/pull/271 이 pr 반영되면 머지하겠습니다

snutt static pages routing

---

apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

Reverts wafflestudio/waffle-world#208

Revert "snutt prod replicas 0으로 설정"

---

apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

Reverts wafflestudio/waffle-world#215

Revert "snutt 서버 차단 해제"

---

apps/snutt-prod/snutt-timetable/snutt-timetable.yaml

Reverts wafflestudio/waffle-world#216

Revert "Revert "snutt 서버 차단 해제""

---

apps/snutt-prod/snutt-ev-batch/snutt-ev-batch.yaml
apps/snutt-prod/snutt-timetable-batch/snutt-timetable-batch.yaml

Reverts wafflestudio/waffle-world#212

Revert "배치 임시 차단"

---

apps/snutt-dev/snutt-timetable/snutt-timetable.yaml

https://github.com/wafflestudio/snutt-timetable/pull/262

snutt dev coursebooks api routing

---

apps/waffledotcom-dev/waffledotcom-server/waffledotcom-server.yaml
apps/waffledotcom-prod/waffledotcom-server/waffledotcom-server.yaml

와플닷컴 서버에 readiness, liveness, statup Probe 를 추가합니다.
[관련 commit](https://github.com/wafflestudio/waffledotcom-server/commit/ac21bbaeec1690593bc095925acd4ca1f0507c6b)

와플닷컴 서버 Readinessprobe 등 추가

---

apps/snutt-dev/snutt-timetable/snutt-timetable.yaml

참고: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1739094985550429

snutt 테마마켓 프론트엔드 dev 서버 CORS origin 허용

---

apps/siksha-dev/siksha-spring-server/siksha-spring-server.yaml

`siksha-dev/siksha-spring-server` 에 발생하고 있는 OOM을 수정합니다.
https://wafflestudio.slack.com/archives/C01M4TMNFPX/p1742123080566889

fix siksha-spring-server oom

---

apps/internhasha-dev/internhasha/internhasha-server.yaml
apps/internhasha-prod/internhasha/internhasha-server.yaml

- 개발과 배포 서버의 프로필 설정을 위한 env 필드를 추가하였습니다
- AWS Secrets Manager 접근을 위한 IAM 역할을 불러오는 Service Account를 추가하였습니다.
- replicas가 다시 1로 증가하였습니다.

인턴하샤 서버에 profile & service account 추가

---

apps/internhasha-dev/internhasha/internhasha-server.yaml
apps/internhasha-prod/internhasha/internhasha-server.yaml

- OOMKilled Errors(137)을 해결하기 위해서 메모리 상한선을 설정했습니다.
- dev 서버 메모리를 256Mi로 늘렸습니다

인턴하샤 서버에 JAVA_OPTS 추가

---

apps/internhasha-dev/internhasha/internhasha-server.yaml
apps/internhasha-prod/internhasha/internhasha-server.yaml

- JAVA_OPTS 필드에 잘못 쓰인 문자열("")을 수정했습니다.

인턴하샤 - JAVA_OPTS 필드 문법 교정

---

apps/internhasha-dev/internhasha/internhasha-server.yaml
apps/internhasha-prod/internhasha/internhasha-server.yaml

- OOM Kill을 방지하기 위해 리소스를 증가시켰습니다.

인턴하샤 - CPU, 메모리 리소스 증가

---

apps/siksha-dev/siksha-spring-server/siksha-spring-server.yaml

- siksha-spring-server dev의 host를 변경하는 PR입니다.
- 기존에 pod 배포 시 host를 임시로 적어두었는데, 내부 논의 하에 url 확정하였습니다
- Route53 등록도 요청드립니다.

chore: 식샤 스프링 서버 host 변경

---

misc/kube-system/configmap/aws-auth.yaml

- Slack: https://wafflestudio.slack.com/archives/C07M61YEC67/p1753444424909539
- 커밋은 기록용이고, 실제 적용은 kubectl apply 로 할 예정입니다

aws-auth에 IAM 추가

---

apps/memowithtags-dev/memowithtags/memowithtags-server.yaml
apps/memowithtags-prod/memowithtags/memowithtags-server.yaml

AWS에 등록한 도메인과 다른 점을 발견하여 도메인을 수정했습니다.

memowithtags 도메인 수정

---

apps/wacruit-dev/wacruit-server/wacruit-server.yaml

increase wacruit-server-dev memory to 256MB

---

apps/snutt-dev/snutt-ev/snutt-ev.yaml
apps/snutt-dev/snutt-timetable/snutt-timetable.yaml

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1754891743798259

snutt-dev ram percentage 75로 조정

---

apps/hodu-dev/hodu/hodu-server.yaml
apps/hodu-prod/hodu/hodu-server.yaml
apps/memowithtags-dev/memowithtags/memowithtags-server.yaml

루키 모집이 끝나서 채점서버는 내려도 되고, memowithtags 팀은 이번 학기 동안은 활동을 하지 않을 거라고 전달받았습니다 (추후 팀빌딩 예정이므로 삭제 X)

미사용 서비스 replica 0으로 설정

---

apps/wacruit-dev/wacruit-server/wacruit-server.yaml
apps/wacruit-prod/wacruit-server/wacruit-server.yaml

wacruit에 arm64 nodeSelector 추가

---

apps/internhasha-dev/internhasha/internhasha-server.yaml
apps/internhasha-prod/internhasha/internhasha-server.yaml

ecr 태그가 이상해진거 같아서 바로잡습니다
https://github.com/wafflestudio/waffle-world/commit/e16b18e8b483c89a007f4eea0be7f07044f7aa53
https://github.com/wafflestudio/waffle-world/commit/829ea85334bd7575052ee95145ba18ce790649cb
태그에 latest는 넣지 않아야 하는거같아요

internhasha yaml 오류 수정

---

apps/wacruit-prod/wacruit-server/wacruit-server.yaml

Fix prod wacruit-server virtualservice hosts

---

apps/siksha-dev/siksha-api-server/siksha-api-server.yaml

안녕하세요, arm64로 빌드 수정하는 과정에서 이미지 푸시가 잘못되어, 수동으로 이미지 URI 수정하였습니다.

식샤 dev 서버 image uri 수정

---

apps/values.yaml

arm 전환이 완료되어 자동 sync를 재활성화하는 pr입니다.

ArgoCD 자동 sync 재활성화

---

apps/internhasha-dev/internhasha/internhasha-server.yaml

Updated the replica count and adjusted memory request.

테스트를 위해 인턴하샤-dev replica 및 memory request 조정

---

apps/internhasha-dev/internhasha/internhasha-server.yaml

테스트를 위해 올려두었던 internhasha 레플리카를 0으로 내렸습니다.

internhasha-dev 레플리카 0으로 재조정
